db:
  image: postgres
redis:
  image: redis
web:
  build: .
  command: paver docker_run
  working_dir: /srv/omaha
  privileged: true
  links:
   - db
   - redis
  ports:
   - "9090:80"
  volumes:
   - ./:/srv/omaha
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: postgres
    DB_NAME: postgres
    DB_PASSWORD: ''
    HOST_NAME: '*'
    SECRET_KEY: 'SECRET_KEY'
    DJANGO_SETTINGS_MODULE: 'omaha_server.settings'
    AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
    AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
    AWS_STORAGE_BUCKET_NAME: 'aws_storage_bucket_name'
    REDIS_HOST: redis
    REDIS_PORT: 6379
    UWSGI_PROCESSES: 10
    UWSGI_THREADS: 8
